Get the passphrase from the terminal.

diff --git a/src/commands/generate b/src/commands/generate
--- a/src/commands/generate
+++ b/src/commands/generate
@@ -34,8 +34,26 @@ validate(){
   fi
 }
 
+get_passphrase() {
+    local passphrase passphrase_again
+    while true; do
+        read -r -p "Enter passphrase for the new key: " -s passphrase || return
+        echo
+        read -r -p "Retype the passphrase of the key: " -s passphrase_again || return
+        echo
+        if [[ "$passphrase" == "$passphrase_again" ]]; then
+            PASSPHRASE="$passphrase"
+            break
+        else
+            echo "Error: the entered passphrases do not match."
+        fi
+    done
+}
+
 invoke(){
-  echo "Creating the key - you'll be asked for a password. Make it a good one."
+    echo -e "\nCreating a new key - you'll be asked for a passphrase. Make it a good one.\n"
+    get_passphrase
+
   $GNUPG -q --batch --gen-key <<-PARAM
 Key-Type: RSA
 Key-Length: 4096
@@ -45,23 +63,22 @@ Name-Comment: $comment
 Name-Email: $email
 Expire-Date: 0
 Preferences: SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 ZLIB BZIP2 ZIP Uncompressed
-%ask-passphrase
-%commit
+Passphrase: $PASSPHRASE
 PARAM
   [[ $? != 0 ]] && return 1
 
   # set up some sub keys, in order not to use the base key day-to-day
   local COMMANDS=$(echo "addkey|4|4096|2y|addkey|6|4096|2y|save" | tr '|' "\n")
-  script -c "$GNUPG --command-fd=0 --edit-key $email <<< \"$COMMANDS\"" >/dev/null
+  script -c "echo -e \"$PASSPHRASE\n$COMMANDS\" | $GNUPG --batch --passphrase-fd=0 --command-fd=0 --edit-key $email" >/dev/null
   RETVAL=$?
 
   # generate a revokation certificate
   get_my_key
   revoke_path="${GNUPGHOME}/${MY_KEY}-revoke.gpg.asc"
-  echo $revoke_path
-  COMMANDS=$(echo "y|1|Revocation generated along with key ahead of need.|y" | tr '|' "\n")
-  script -c "$GNUPG --command-fd=0 --output \"${revoke_path}\" --gen-revoke $email <<< \"$COMMANDS\"" >/dev/null
-  [[ $? -ne 0 ]] && RETVAL=$?
+  COMMANDS=$(echo "y|1|Revocation generated along with key ahead of need.||y" | tr '|' "\n")
+  script -c "echo -e \"$COMMANDS\" | $GNUPG --command-fd=0 --output $revoke_path --gen-revoke $email" >/dev/null
+  [[ $? -ne 0 ]] && RETVAL=$? && exit 1
+  echo "Revocation certificate: $revoke_path"
 
 #  #For development purposes
 #  send_command= "$GNUPG --keyserver hkp://keys.gnupg.net --send-keys $email"
